### ISSUE TITLE
Grafana pods do not come out of pending

### ISSUE THREAD

**Issue by despossivel** [felipeagger/k8s-all-in-one#1]
grafana pods don't leave Pending, I've waited more than hours and nothing to work for me.

Can anyone tell me something about this?

**Comment by despossivel** [comment]
@felipeagger

**Comment by despossivel** [comment]
![image](https://user-images.githubusercontent.com/10657158/95501504-cc1e5000-097e-11eb-9b52-c7844cb65e86.png)

**Comment by despossivel** [comment]
I have my cluster in GCP

**Comment by felipeagger** [comment]
Troubleshoot this pod: 

kubectl logs grafana-7fb...
kubectl describe pods grafana-7fb...

and comment here the result.
I already had a similar problem, that I could not download the image of the grafana.

**Comment by despossivel** [comment]
sorry for the delay but the pod is never found

Error from server (NotFound): pods "grafana-7fbf468cf8-887sp" not found

**Comment by despossivel** [comment]
but I noticed that the graphana deployment is not ready 

![image](https://user-images.githubusercontent.com/10657158/95686764-70e69a80-0bd6-11eb-8e9e-3a1de1d3830b.png)

**Comment by despossivel** [comment]
@felipeagger  I believe it is some limitation of my cluster, I made some adaptations and it worked

**Comment by despossivel** [comment]
I managed to make it work for me, but the dashboard does not display data.

Do you know what I might be doing wrong?

![image](https://user-images.githubusercontent.com/10657158/95691901-26c2e080-0bf9-11eb-9fd7-bc56fb130ad5.png)

**Comment by felipeagger** [comment]
See this tutorial: https://youtu.be/HiIV-TyS-O8

Check if Prometheus stay running and collecting data of nodes.
